import { hashSync } from 'bcryptjs';
import type { ControlPlaneState } from './control-plane.types';

const anchor = new Date('2026-05-22T23:55:00.000Z');
const plusDays = (days: number) =>
  new Date(anchor.getTime() + days * 24 * 60 * 60 * 1000).toISOString();
const minusDays = (days: number) =>
  new Date(anchor.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const seedState: ControlPlaneState = {
  users: [
    {
      id: 'usr_admin',
      email: 'ops@hysteria.local',
      displayName: 'Operations Admin',
      passwordHash: hashSync('admin123!', 10),
      role: 'admin',
      status: 'active',
      notes: 'Primary operator account',
      createdAt: minusDays(120),
      updatedAt: minusDays(1),
    },
    {
      id: 'usr_lin',
      email: 'lin@example.com',
      displayName: 'Lin',
      passwordHash: hashSync('member123!', 10),
      role: 'member',
      status: 'active',
      notes: 'Starter seed account',
      createdAt: minusDays(45),
      updatedAt: minusDays(1),
    },
    {
      id: 'usr_zhou',
      email: 'zhou@example.com',
      displayName: 'Zhou',
      passwordHash: hashSync('member123!', 10),
      role: 'member',
      status: 'suspended',
      notes: 'Used to demo enforcement states',
      createdAt: minusDays(30),
      updatedAt: minusDays(2),
    },
  ],
  accessTokens: [
    {
      id: 'tok_lin',
      userId: 'usr_lin',
      label: 'Primary access token',
      token: 'hy2_live_lin_primary',
      createdAt: minusDays(30),
      lastUsedAt: minusDays(1),
    },
    {
      id: 'tok_zhou',
      userId: 'usr_zhou',
      label: 'Suspended account token',
      token: 'hy2_live_zhou_primary',
      createdAt: minusDays(20),
      lastUsedAt: minusDays(3),
    },
  ],
  plans: [
    {
      id: 'plan_core',
      slug: 'core-200',
      name: 'Core 200',
      description: '200GB quota, 30-day cycle, 3 devices',
      active: true,
      trafficBytes: 200 * 1024 * 1024 * 1024,
      durationDays: 30,
      speedUpMbps: 20,
      speedDownMbps: 120,
      deviceLimit: 3,
      priceCents: 1800,
      accent: 'green',
      createdAt: minusDays(100),
      updatedAt: minusDays(1),
    },
    {
      id: 'plan_pro',
      slug: 'pro-500',
      name: 'Pro 500',
      description: '500GB quota, 30-day cycle, 5 devices',
      active: true,
      trafficBytes: 500 * 1024 * 1024 * 1024,
      durationDays: 30,
      speedUpMbps: 40,
      speedDownMbps: 240,
      deviceLimit: 5,
      priceCents: 3200,
      accent: 'teal',
      createdAt: minusDays(98),
      updatedAt: minusDays(1),
    },
  ],
  nodeGroups: [
    {
      id: 'grp_core',
      slug: 'core-tier',
      name: 'Core Tier',
      description: 'Entry tier listeners with fixed 20/120 Mbps ceilings',
      active: true,
      createdAt: minusDays(100),
      updatedAt: minusDays(1),
    },
    {
      id: 'grp_pro',
      slug: 'pro-tier',
      name: 'Pro Tier',
      description: 'Higher-throughput listeners with dedicated ports',
      active: true,
      createdAt: minusDays(100),
      updatedAt: minusDays(1),
    },
  ],
  nodes: [
    {
      id: 'node_hk_core',
      nodeGroupId: 'grp_core',
      label: 'HK-01 Core :4431',
      hostname: 'hk-01.example.net',
      port: 4431,
      obfsPassword: 'salty-core',
      sni: 'edge.example.net',
      pinSHA256: 'AA:11:22:33:44:55',
      allowInsecureTls: false,
      trafficApiBaseUrl: 'mock://hk-core',
      trafficApiSecret: 'stats-core',
      active: true,
      speedUpMbps: 20,
      speedDownMbps: 120,
      createdAt: minusDays(90),
      updatedAt: minusDays(1),
    },
    {
      id: 'node_sg_core',
      nodeGroupId: 'grp_core',
      label: 'SG-01 Core :4432',
      hostname: 'sg-01.example.net',
      port: 4432,
      obfsPassword: 'salty-core',
      sni: 'edge.example.net',
      pinSHA256: 'AA:11:22:33:44:56',
      allowInsecureTls: false,
      trafficApiBaseUrl: 'mock://sg-core',
      trafficApiSecret: 'stats-core',
      active: true,
      speedUpMbps: 20,
      speedDownMbps: 120,
      createdAt: minusDays(90),
      updatedAt: minusDays(1),
    },
    {
      id: 'node_hk_pro',
      nodeGroupId: 'grp_pro',
      label: 'HK-02 Pro :5443',
      hostname: 'hk-02.example.net',
      port: 5443,
      obfsPassword: 'salty-pro',
      sni: 'pro-edge.example.net',
      pinSHA256: 'BB:66:77:88:99:00',
      allowInsecureTls: false,
      trafficApiBaseUrl: 'mock://hk-pro',
      trafficApiSecret: 'stats-pro',
      active: true,
      speedUpMbps: 40,
      speedDownMbps: 240,
      createdAt: minusDays(90),
      updatedAt: minusDays(1),
    },
  ],
  planBindings: [
    {
      id: 'bind_core',
      planId: 'plan_core',
      nodeGroupId: 'grp_core',
      priority: 0,
      createdAt: minusDays(100),
    },
    {
      id: 'bind_pro',
      planId: 'plan_pro',
      nodeGroupId: 'grp_pro',
      priority: 0,
      createdAt: minusDays(100),
    },
  ],
  subscriptions: [
    {
      id: 'sub_lin',
      userId: 'usr_lin',
      planId: 'plan_core',
      nodeGroupId: 'grp_core',
      status: 'active',
      startsAt: minusDays(10),
      endsAt: plusDays(20),
      includedTrafficBytes: 200 * 1024 * 1024 * 1024,
      bonusTrafficBytes: 15 * 1024 * 1024 * 1024,
      consumedTrafficBytes: 86 * 1024 * 1024 * 1024,
      speedUpMbpsSnapshot: 20,
      speedDownMbpsSnapshot: 120,
      deviceLimitSnapshot: 3,
      createdAt: minusDays(10),
      updatedAt: minusDays(1),
    },
    {
      id: 'sub_zhou',
      userId: 'usr_zhou',
      planId: 'plan_pro',
      nodeGroupId: 'grp_pro',
      status: 'paused',
      startsAt: minusDays(18),
      endsAt: plusDays(12),
      includedTrafficBytes: 500 * 1024 * 1024 * 1024,
      bonusTrafficBytes: 0,
      consumedTrafficBytes: 15 * 1024 * 1024 * 1024,
      speedUpMbpsSnapshot: 40,
      speedDownMbpsSnapshot: 240,
      deviceLimitSnapshot: 5,
      createdAt: minusDays(18),
      updatedAt: minusDays(2),
    },
  ],
  trafficPacks: [
    {
      id: 'pack_lin',
      userId: 'usr_lin',
      subscriptionId: 'sub_lin',
      label: 'May booster',
      totalBytes: 50 * 1024 * 1024 * 1024,
      remainingBytes: 34 * 1024 * 1024 * 1024,
      status: 'active',
      expiresAt: plusDays(15),
      createdAt: minusDays(7),
      updatedAt: minusDays(1),
    },
  ],
  manualOrders: [
    {
      id: 'ord_lin_boost',
      userId: 'usr_lin',
      processedById: 'usr_admin',
      status: 'applied',
      kind: 'traffic_pack',
      amountCents: 900,
      trafficBytes: 50 * 1024 * 1024 * 1024,
      note: 'Manual booster top-up',
      createdAt: minusDays(7),
      processedAt: minusDays(7),
    },
  ],
  authEvents: [],
  usageRollups: [
    {
      id: 'usage_seed_lin',
      userId: 'usr_lin',
      subscriptionId: 'sub_lin',
      nodeId: 'node_hk_core',
      bucketStart: minusDays(1),
      txBytes: 12 * 1024 * 1024 * 1024,
      rxBytes: 24 * 1024 * 1024 * 1024,
      source: 'seed',
      createdAt: minusDays(1),
    },
  ],
  onlineSnapshots: [
    {
      id: 'snap_lin_hk',
      userId: 'usr_lin',
      nodeId: 'node_hk_core',
      concurrentClients: 2,
      capturedAt: anchor.toISOString(),
    },
  ],
};
